import { useContext } from "react";
import Head from "next/head";
import { ContrastContext } from "../../providers/Context";
import { Container } from "@mui/material";
import NavbarDesktop from "@/components/NavbarDesktop";

const Contato = () => {
    const {isDisabled} = useContext(ContrastContext );

    return(
        <>
            <Head>
                <title>Guilherme Rocha Leite - Portfólio</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="page flex">
                <NavbarDesktop />
                <Container className="container" maxWidth="xl">
                    <h1>{isDisabled.toString()}</h1>
                </Container>
            </main>
        </>
    )
}

export default Contato;