import Head from "next/head";
import { Box, Button, Container, Modal, Snackbar, Typography, useMediaQuery } from "@mui/material";
import NavbarDesktop from "@/components/NavbarDesktop";
import styles from './styles.module.scss';
import { useRef, useState } from "react";
import { socialItems } from "@/providers/ItemsList";

export const config = {
    api: {
      bodyParser: false,
    },
};

const Contato = () => {
    const maxCharacters = 500;
    const inputFile = useRef<HTMLInputElement>(null);
    const btnSubmit = useRef<HTMLButtonElement>(null);
    const charactersSpan = useRef<HTMLSpanElement>(null);
    const [charactersLeft, setCharactersLeft] = useState<number>(maxCharacters);
    const [file, setFile] = useState<File | null>(null);
    const [name, setName] = useState<string>("");
    const [email, setEmail] = useState<string>("");
    const [phone, setPhone] = useState<string>("");
    const [message, setMessage] = useState<string>("");
    const [sent, setSent] = useState<boolean>(false);
    const [modalOpen, setModalOpen] = useState<boolean>(false);
    const isMobile = useMediaQuery('(max-width:1024px)');

    function handleChange(event: any){
        setFile(event?.target?.files[0]);        
        ValidaArquivo(event?.target?.files[0]);
    }

    function ValidaArquivo(file: File) {
        var tamanhoArquivo = file?.size / 1024 / 1024; // in MB
        var tiposArquivo = ['image/png', 'image/jpeg', 'image/jpg', 'application/pdf'];

        if(tamanhoArquivo == 0){
            setFile(null);
        }
        if (tamanhoArquivo > 4) {
            alert('O arquivo excede a 4 MB');
            btnSubmit.current?.setAttribute("disabled", "disabled");
            inputFile.current?.setAttribute("value", "");
            setFile(null);
        } else {
            for (let i = 0; i < tiposArquivo.length; i++) {
                if (file?.type === tiposArquivo[i]) {
                    i=tiposArquivo.length;
                    btnSubmit.current?.removeAttribute("disabled");
                }

                else if(i===tiposArquivo.length-1){
                    alert('Tipo de arquivo não permitido (JPG, PNG, JPEG ou PDF)');
                    btnSubmit.current?.setAttribute("disabled", "disabled");
                    inputFile.current?.setAttribute("value", "");
                    setFile(null);
                }
            }
        }
    }

    function limitTextarea(event: any) {
        if(charactersSpan.current){
            const valor = event.target.value;
            const total = valor.length;
            if(total <= maxCharacters) {
                let resto = maxCharacters - total;
                setCharactersLeft(resto);
                if(resto <= 15){
                    charactersSpan.current.classList.add(styles.limit);
                } else{
                    charactersSpan.current.classList.remove(styles.limit);
                }
            } else {
                setCharactersLeft(valor.substr(0, maxCharacters));
            }
        }
        
    }

    function handleName(e: any){
        setName(e?.target?.value);
    }

    function handleEmail(e: any){
        setEmail(e?.target?.value);
    }

    function handlePhone(e: any){
        setPhone(e?.target?.value);
    }

    function handleMessage(e: any){
        setMessage(e?.target?.value);
    }

    function handleOpenModal(){
        sent && clearFields();
        setModalOpen(true);
        setTimeout(handleCloseModal, 15000);
    }
    
    function handleCloseModal(){
        setModalOpen(false);
    }

    async function sendMail(e: any){
        e.preventDefault();
        const url = `${process.env.NEXT_PUBLIC_MAIL_SERVER}/api/send`;
        
        try{
            const resp = await fetch(url, {
                method: "POST",
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({
                    name,
                    email,
                    phone,
                    message
                })
            })
            
            const isSent = await resp.status;
            setSent(isSent === 200);
            handleOpenModal();
        } catch(error){
            setSent(false);
            handleOpenModal();
        }
    }

    function clearFields(){
        setName("");
        setEmail("");
        setPhone("");
        setMessage("")
        setFile(null);
    }

    return(
        <>
            <Head>
                <title>Guilherme Rocha Leite - Portfólio</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="page flex">
                <NavbarDesktop />
                <Container maxWidth="xl">
                    <h3 className={styles.contactTitle}>Envie uma mensagem</h3>

                    <section className={styles.sectionContact}>
                        <form method="POST" className={styles.contactForm} onSubmit={sendMail}>
                            <Box className={styles.contactFormBody}>
                                <Box className={`${styles.formLine}`}>
                                    <fieldset>
                                        <label htmlFor="nome_autor">Nome
                                            <span className="required">*</span>
                                        </label>
                                        <input 
                                        type="text" 
                                        placeholder="Nome" 
                                        name="nome_autor" 
                                        id="nome_autor"
                                        required
                                        onChange={handleName}    
                                        value={name}
                                    />
                                    </fieldset>

                                    <fieldset>
                                        <label htmlFor="email_autor">E-mail
                                            <span className="required">*</span>
                                        </label>
                                        <input 
                                        type="email" 
                                        placeholder="E-mail" 
                                        name="email_autor" 
                                        id="email_autor" 
                                        required
                                        onChange={handleEmail}
                                        value={email}
                                    />
                                    </fieldset>

                                    <fieldset>
                                        <label htmlFor="telefone_autor">Telefone</label>
                                        <input 
                                            type="text" 
                                            id="telefone_autor" 
                                            placeholder="Telefone" 
                                            name="telefone_autor" 
                                            onChange={handlePhone}
                                            value={phone}    
                                        />
                                    </fieldset>
                                </Box>

                                <Box className={styles.formBlock}>
                                    <Box>
                                        <span ref={charactersSpan} className={styles.charactersLeft}>{charactersLeft}</span>
                                        <span>Restantes</span>  
                                        <span className="required">*</span>
                                    </Box>
                                    <fieldset>
                                        <textarea 
                                            maxLength={maxCharacters} 
                                            rows={3} 
                                            cols={6} 
                                            placeholder="Mensagem" 
                                            name="conteudo" 
                                            id="texto" 
                                            required
                                            onKeyUp={limitTextarea}
                                            onChange={handleMessage}
                                            value={message}
                                        ></textarea>
                                        {!file?.name ? 
                                            <input
                                                style={{
                                                    display: "none"
                                                }}
                                                value=""
                                                ref={inputFile} 
                                                onChange={handleChange} 
                                                name="arquivo" 
                                                type="file" 
                                                id="arquivo" 
                                            />
                                        : 
                                            <input
                                                style={{
                                                    display: "none"
                                                }}
                                                ref={inputFile} 
                                                onChange={handleChange} 
                                                name="arquivo" 
                                                type="file" 
                                                id="arquivo" 
                                            />
                                        }
                                    </fieldset>
                                </Box>
                            </Box>

                            <Box className={styles.submitArea}>
                                <Button ref={btnSubmit} type="submit">
                                    Enviar Mensagem
                                </Button>
                            </Box>
                        </form>
                    </section>

                    <section className={styles.sectionContact}>
                        <Typography className={styles.visitarPerfis}>
                            Visite meu perfil nas redes sociais:
                        </Typography>

                        {socialItems.length && 
                            <ul className={styles.socialItems}>
                                {socialItems.map((item, key) => (
                                    <li key={key}>
                                        <a title={item.name} href={item.link} target="_blank">
                                            {item.icon}
                                        </a>
                                    </li>
                                ))}
                            </ul>
                        }
                    </section>

                    <Modal
                        open={modalOpen}
                        onClose={handleCloseModal}
                        aria-labelledby="modal-modal-title"
                        aria-describedby="modal-modal-description"
                        
                        sx={
                            isMobile ? 
                            {
                                display: "flex",
                                justifyContent: "center"
                            }
                            :
                            {
                                display: "flex",
                                justifyContent: "center",
                                left: "17rem"
                            }
                        } 
                    >
                        <Box className={`${sent ? styles.success : styles.fail} ${styles.modalContainer}`}>
                            <Typography className={styles.modalText}>
                                {sent ? 
                                "Mensagem enviada com sucesso!" 
                                : 
                                <>
                                    <Typography className={styles.modalText} style={{
                                        marginBottom: "10px"
                                    }}>Ocorreu um erro ao enviar a mensagem... 😕️</Typography>
                                    <Typography className={styles.modalText}>Favor entrar em contato por alguma rede social</Typography>
                                </>
                                
                                }
                            </Typography>
                        </Box>
                    </Modal>
                </Container>
            </main>
        </>
    )
}

export default Contato;