import Head from "next/head";
import styles from "./Home.module.scss";
import { ContrastContext } from "@/providers/Context";
import { useContext } from "react";

export default function Home() {
  const {isDisabled} = useContext(ContrastContext);

  return (
    <>
      <Head>
        <title>Guilherme Rocha Leite - Portfólio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className={styles.h1}>{isDisabled.toString()}</h1>
      </main>
    </>
  );
}
